const hotels = [
    // United Kingdom
    { name: "The Langham", address: "1C Portland Place, London W1B 1JA", starRating: 5, country: "United Kingdom" },
    { name: "The Ritz", address: "150 Piccadilly, London W1J 9BR", starRating: 5, country: "United Kingdom" },
    { name: "The Savoy", address: "Strand, London WC2R 0EZ", starRating: 5, country: "United Kingdom" },
    { name: "Claridge's", address: "Brook Street, London W1K 4HR", starRating: 5, country: "United Kingdom" },
    { name: "The Dorchester", address: "53 Park Lane, London W1K 1QA", starRating: 5, country: "United Kingdom" },
    { name: "The Hoxton", address: "81 Great Eastern Street, London EC2A 3HU", starRating: 4, country: "United Kingdom" },
    { name: "The Zetter Townhouse", address: "49-50 St John's Square, London EC1V 4JJ", starRating: 4, country: "United Kingdom" },
    { name: "Radisson Blu Edwardian", address: "97 Great Russell Street, London WC1B 3LB", starRating: 4, country: "United Kingdom" },
    { name: "Hotel Café Royal", address: "68 Regent Street, London W1B 4DY", starRating: 4, country: "United Kingdom" },
    { name: "Hotel Indigo", address: "1 Leicester Place, London WC2H 7BP", starRating: 4, country: "United Kingdom" },
    { name: "The Nadler Victoria", address: "10 Palace Street, London SW1E 5BW", starRating: 3, country: "United Kingdom" },
    { name: "Premier Inn London City (Aldgate)", address: "66 Alie Street, London E1 8PX", starRating: 3, country: "United Kingdom" },
    { name: "ibis London Blackfriars", address: "49 Blackfriars Road, London SE1 8NZ", starRating: 3, country: "United Kingdom" },
    { name: "The Best Western Plus London Wembley", address: "365 High Road, Wembley HA9 6AY", starRating: 3, country: "United Kingdom" },
    { name: "The Z Hotel Shoreditch", address: "136-144 City Road, London EC1V 2RL", starRating: 3, country: "United Kingdom" },

    // France
    { name: "The Ritz", address: "15 Place Vendôme, 75001 Paris", starRating: 5, country: "France" },
    { name: "Le Meurice", address: "228 Rue de Rivoli, 75001 Paris", starRating: 5, country: "France" },
    { name: "Hôtel Plaza Athénée", address: "25 Avenue Montaigne, 75008 Paris", starRating: 5, country: "France" },
    { name: "Four Seasons Hotel George V", address: "31 Avenue George V, 75008 Paris", starRating: 5, country: "France" },
    { name: "Shangri-La Paris", address: "10 Avenue d'Iéna, 75116 Paris", starRating: 5, country: "France" },
    { name: "Le Relais Saint-Germain", address: "9 Carrefour de l'Odéon, 75006 Paris", starRating: 4, country: "France" },
    { name: "Hotel La Villa Saint-Germain-des-Prés", address: "29 Rue Jacob, 75006 Paris", starRating: 4, country: "France" },
    { name: "Hotel Lutetia", address: "45 Boulevard Raspail, 75006 Paris", starRating: 4, country: "France" },
    { name: "Hotel Le Petit Moulin", address: "29/31 Rue de Poitou, 75003 Paris", starRating: 4, country: "France" },
    { name: "Hôtel le 123 Sébastopol", address: "123 Boulevard de Sébastopol, 75002 Paris", starRating: 4, country: "France" },
    { name: "Hôtel La Demeure", address: "51 Boulevard Saint-Marcel, 75013 Paris", starRating: 3, country: "France" },
    { name: "Hôtel du Champs-Élysées", address: "140 Avenue des Champs-Élysées, 75008 Paris", starRating: 3, country: "France" },
    { name: "Hôtel de la Herse d'Or", address: "6 Rue de la Herse, 75004 Paris", starRating: 3, country: "France" },
    { name: "Hôtel Elysée Montmartre", address: "18 Rue du Mont-Cenis, 75018 Paris", starRating: 3, country: "France" },
    { name: "Hôtel du Lion", address: "2 Rue du Montparnasse, 75006 Paris", starRating: 3, country: "France" },

    // Italy
    { name: "Hotel Danieli", address: "Riva degli Schiavoni, 4196, 30122 Venice", starRating: 5, country: "Italy" },
    { name: "Hotel Hassler", address: "Piazza Trinità dei Monti, 6, 00187 Rome", starRating: 5, country: "Italy" },
    { name: "Belmond Hotel Cipriani", address: "Giudecca 10, 30133 Venice", starRating: 5, country: "Italy" },
    { name: "Four Seasons Hotel Milano", address: "Via Gesù, 6/8, 20121 Milan", starRating: 5, country: "Italy" },
    { name: "Grand Hotel Tremezzo", address: "Via Roma, 8, 22016 Tremezzo", starRating: 5, country: "Italy" },
    { name: "Hotel Artemide", address: "Via Nazionale, 22, 00184 Rome", starRating: 4, country: "Italy" },
    { name: "Starhotels Anderson", address: "Piazza Luigi di Savoia, 20, 20124 Milan", starRating: 4, country: "Italy" },
    { name: "Hotel Brunelleschi", address: "Piazza Santa Elisabetta, 3, 50122 Florence", starRating: 4, country: "Italy" },
    { name: "Hotel L’Orologio", address: "Piazza Santa Maria Novella, 24, 50123 Florence", starRating: 4, country: "Italy" },
    { name: "Hotel La Pace", address: "Viale Gramsci, 14, 56125 Pisa", starRating: 4, country: "Italy" },
    { name: "Hotel Edera", address: "Via Vicenza, 34, 00185 Rome", starRating: 3, country: "Italy" },
    { name: "Hotel Al Ponte Mocenigo", address: "Campo San Stae, 1995, 30135 Venice", starRating: 3, country: "Italy" },
    { name: "Hotel Milano", address: "Via Nazionale, 22, 50123 Florence", starRating: 3, country: "Italy" },
    { name: "Hotel De La Ville", address: "Via Cusani, 6, 20121 Milan", starRating: 3, country: "Italy" },
    { name: "Hotel San Remo", address: "Via dei Serpenti, 109, 00184 Rome", starRating: 3, country: "Italy" },

    // Germany
    { name: "Hotel Adlon Kempinski", address: "Unter den Linden 77, 10117 Berlin", starRating: 5, country: "Germany" },
    { name: "The Ritz-Carlton", address: "Potsdamer Platz 3, 10785 Berlin", starRating: 5, country: "Germany" },
    { name: "Bulgari Hotel", address: "Brandenburger Tor, 10117 Berlin", starRating: 5, country: "Germany" },
    { name: "Hotel Atlantic Kempinski", address: "An der Alster 72-79, 20099 Hamburg", starRating: 5, country: "Germany" },
    { name: "Bayerischer Hof", address: "Promenadeplatz 2-6, 80333 Munich", starRating: 5, country: "Germany" },
    { name: "Motel One Berlin-Alexanderplatz", address: "Alexanderplatz 9, 10178 Berlin", starRating: 4, country: "Germany" },
    { name: "NH Collection Berlin Mitte", address: "Leipziger Straße 106-111, 10117 Berlin", starRating: 4, country: "Germany" },
    { name: "Maritim Hotel", address: "Theodor-Heuss-Allee 3, 60486 Frankfurt", starRating: 4, country: "Germany" },
    { name: "Steigenberger Hotel", address: "Bayerstraße 12, 80335 Munich", starRating: 4, country: "Germany" },
    { name: "Hotel Europäischer Hof", address: "Friedrich-Ebert-Anlage 1, 69117 Heidelberg", starRating: 4, country: "Germany" },
    { name: "Hotel Berlin", address: "Lützowplatz 17, 10785 Berlin", starRating: 3, country: "Germany" },
    { name: "ibis Styles Hamburg Alster City", address: "Mühlendamm 1, 22087 Hamburg", starRating: 3, country: "Germany" },
    { name: "Hotel Amadeus", address: "Amadeusstraße 5, 60325 Frankfurt", starRating: 3, country: "Germany" },
    { name: "Holiday Inn Express", address: "Schwanthalerstraße 121, 80339 Munich", starRating: 3, country: "Germany" },
    { name: "Hotel Ibis", address: "Bismarckstraße 19, 69115 Heidelberg", starRating: 3, country: "Germany" },

    // Spain
    { name: "Hotel Ritz", address: "Plaza de la Lealtad, 5, 28014 Madrid", starRating: 5, country: "Spain" },
    { name: "The One Barcelona", address: "Carrer de Provença, 277, 08008 Barcelona", starRating: 5, country: "Spain" },
    { name: "Hotel Alfonso XIII", address: "Calle San Fernando, 2, 41004 Seville", starRating: 5, country: "Spain" },
    { name: "Mandarin Oriental", address: "Passeig de Gràcia, 38-40, 08007 Barcelona", starRating: 5, country: "Spain" },
    { name: "Gran Melia Palacio de los Duques", address: "Cuesta de Santo Domingo, 5, 28013 Madrid", starRating: 5, country: "Spain" },
    { name: "Hotel Barcelona Center", address: "Carrer del Diputació, 234, 08007 Barcelona", starRating: 4, country: "Spain" },
    { name: "H10 Madison", address: "Carrer de Pau Claris, 19, 08010 Barcelona", starRating: 4, country: "Spain" },
    { name: "Hotel Santo Domingo", address: "Calle San Bernardo, 1, 28015 Madrid", starRating: 4, country: "Spain" },
    { name: "NH Collection Madrid Suecia", address: "Calle del Marqués de Casa Riera, 4, 28014 Madrid", starRating: 4, country: "Spain" },
    { name: "Hotel Gran Via", address: "Gran Vía, 25, 28013 Madrid", starRating: 4, country: "Spain" },
    { name: "Hotel Regente", address: "Calle Gran Vía, 51, 28013 Madrid", starRating: 3, country: "Spain" },
    { name: "Hotel Internacional", address: "Carrer de la Boqueria, 21, 08002 Barcelona", starRating: 3, country: "Spain" },
    { name: "Hotel Meliá", address: "Dr. Pedro de Castro, 1, 41004 Seville", starRating: 3, country: "Spain" },
    { name: "Hotel Nouvel", address: "Carrer de Sant Pau, 9-11, 08001 Barcelona", starRating: 3, country: "Spain" },
    { name: "Ibis Madrid Centro", address: "Calle de Valverde, 9, 28004 Madrid", starRating: 3, country: "Spain" },

    // Switzerland
    { name: "Badrutt’s Palace Hotel", address: "Via Serlas 27, 7500 St. Moritz", starRating: 5, country: "Switzerland" },
    { name: "The Dolder Grand", address: "Kurhausstrasse 65, 8032 Zurich", starRating: 5, country: "Switzerland" },
    { name: "Kulm Hotel", address: "Via Claudia Augusta 2, 7500 St. Moritz", starRating: 5, country: "Switzerland" },
    { name: "Hotel des Trois Couronnes", address: "Place du Mont-Pèlerin 34, 1800 Vevey", starRating: 5, country: "Switzerland" },
    { name: "Badrutt’s Palace Hotel", address: "Via Serlas 27, 7500 St. Moritz", starRating: 5, country: "Switzerland" },
    { name: "Hotel Seehof", address: "Seehofstrasse 11, 8008 Zurich", starRating: 4, country: "Switzerland" },
    { name: "Hotel Bristol", address: "10 Rue du Mont-Blanc, 1201 Geneva", starRating: 4, country: "Switzerland" },
    { name: "Hotel Royal", address: "Weinmarkt 12, 6004 Lucerne", starRating: 4, country: "Switzerland" },
    { name: "Swissotel Zurich", address: "Schulstrasse 44, 8050 Zurich", starRating: 4, country: "Switzerland" },
    { name: "Hotel Alina", address: "6 Rue du Mont-Blanc, 1201 Geneva", starRating: 4, country: "Switzerland" },
    { name: "Hotel City", address: "Buckhauserstrasse 36, 8048 Zurich", starRating: 3, country: "Switzerland" },
    { name: "ibis Styles Geneve Mont Blanc", address: "8-10 Rue Ami-Levrier, 1201 Geneva", starRating: 3, country: "Switzerland" },
    { name: "Hotel Ibis Basel", address: "Basel SBB, 4002 Basel", starRating: 3, country: "Switzerland" },
    { name: "Hotel Ibis Luzern", address: "Pilatusstrasse 29, 6003 Lucerne", starRating: 3, country: "Switzerland" },
    { name: "Hotel Adler", address: "Rosengasse 10, 8001 Zurich", starRating: 3, country: "Switzerland" },
    // Ukraine
    { name: "Premier Palace Hotel", address: "5-7/29 T. Shevchenka Blvd., Kyiv", starRating: 5, country: "Ukraine" },
    { name: "InterContinental", address: "2A Velyka Zhytomyrska St, Kyiv", starRating: 5, country: "Ukraine" },
    { name: "Fairmont Grand Hotel", address: "1 Naberezhno-Khreshchatytska St, Kyiv", starRating: 5, country: "Ukraine" },
    { name: "Hyatt Regency", address: "5, A. Tarasova St, Kyiv", starRating: 5, country: "Ukraine" },
    { name: "Hilton", address: "30 Tarasa Shevchenka Blvd, Kyiv", starRating: 5, country: "Ukraine" },
    { name: "Hotel Ukraine", address: "4 Institutskaya St, Kyiv", starRating: 4, country: "Ukraine" },
    { name: "Radisson Blu Hotel", address: "22 Yaroslaviv Val St, Kyiv", starRating: 4, country: "Ukraine" },
    { name: "11 Mirrors Design Hotel", address: "34A Bogdana Khmelnytskogo St, Kyiv", starRating: 4, country: "Ukraine" },
    { name: "Opera Hotel", address: "53 B. Khmelnitskogo St, Kyiv", starRating: 4, country: "Ukraine" },
    { name: "Hotel Dnipro", address: "1/2 Khreshchatyk St, Kyiv", starRating: 3, country: "Ukraine" },
    { name: "ibis Kiev City Center", address: "Taras Shevchenko Blvd, 25, Kyiv", starRating: 3, country: "Ukraine" },
    { name: "Hotel Bakkara", address: "1, Venice Island, Hydropark, Kyiv", starRating: 3, country: "Ukraine" },
    { name: "Hotel Bratislava", address: "1 Malyshko St, Kyiv", starRating: 3, country: "Ukraine" },
    { name: "Hotel Mir", address: "70, Holosiivskyi Ave, Kyiv", starRating: 3, country: "Ukraine" },

    // Poland
    { name: "Raffles Europejski", address: "Krakowskie Przedmieście 13, 00-071 Warsaw", starRating: 5, country: "Poland" },
    { name: "Sheraton Grand", address: "Powiśle 7, 31-101 Kraków", starRating: 5, country: "Poland" },
    { name: "Sofitel Warsaw Victoria", address: "Królewska 11, 00-065 Warsaw", starRating: 5, country: "Poland" },
    { name: "The Westin", address: "Al. Jana Pawła II 21, 00-854 Warsaw", starRating: 5, country: "Poland" },
    { name: "Hotel Bristol, a Luxury Collection Hotel", address: "Krakowskie Przedmieście 42/44, 00-325 Warsaw", starRating: 5, country: "Poland" },
    { name: "PURO Hotel", address: "Ogrodowa 10, 31-155 Kraków", starRating: 4, country: "Poland" },
    { name: "Vienna House Andel’s", address: "Ogrodowa 17, 91-065 Łódź", starRating: 4, country: "Poland" },
    { name: "Radisson Blu Sobieski Hotel", address: "Plac Artura Zawiszy 1, 02-025 Warsaw", starRating: 4, country: "Poland" },
    { name: "Hotel Mercure Wrocław Centrum", address: "Pl. Dominikański 1, 50-159 Wrocław", starRating: 4, country: "Poland" },
    { name: "Holiday Inn Kraków City Centre", address: "Wielopole 4, 31-072 Kraków", starRating: 4, country: "Poland" },
    { name: "Ibis Kraków Stare Miasto", address: "Pawia 15, 31-154 Kraków", starRating: 3, country: "Poland" },
    { name: "Hotel Gromada Warszawa Centrum", address: "Pl. Powstańców Warszawy 2, 00-030 Warsaw", starRating: 3, country: "Poland" },
    { name: "Campanile Wroclaw Centrum", address: "Ślężna 26, 53-302 Wrocław", starRating: 3, country: "Poland" },
    { name: "Hotel Metropol", address: "Marszałkowska 99a, 00-693 Warsaw", starRating: 3, country: "Poland" },
    { name: "Ibis Warszawa Centrum", address: "Al. Solidarności 165, 00-876 Warsaw", starRating: 3, country: "Poland" },

    // Portugal
    { name: "Four Seasons Hotel Ritz", address: "R. Rodrigo da Fonseca 88, 1099-039 Lisbon", starRating: 5, country: "Portugal" },
    { name: "Pestana Palace", address: "Rua Jau 54, 1300-314 Lisbon", starRating: 5, country: "Portugal" },
    { name: "Belmond Reid's Palace", address: "Estrada Monumental 139, 9000-098 Funchal", starRating: 5, country: "Portugal" },
    { name: "The Yeatman", address: "Rua do Choupelo, 4400-088 Vila Nova de Gaia", starRating: 5, country: "Portugal" },
    { name: "Vila Vita Parc Resort & Spa", address: "R. Anneliese Pohl, 8400-450 Porches", starRating: 5, country: "Portugal" },
    { name: "Hotel Avenida Palace", address: "R. 1º de Dezembro 123, 1200-359 Lisbon", starRating: 4, country: "Portugal" },
    { name: "InterContinental Porto - Palacio das Cardosas", address: "Praça da Liberdade 25, 4000-322 Porto", starRating: 4, country: "Portugal" },
    { name: "Pousada de Lisboa", address: "Praça do Comércio 31-34, 1100-148 Lisbon", starRating: 4, country: "Portugal" },
    { name: "PortoBay Liberdade", address: "Rua Rosa Araújo 8, 1250-195 Lisbon", starRating: 4, country: "Portugal" },
    { name: "Altis Avenida Hotel", address: "R. 1º de Dezembro 120, 1200-360 Lisbon", starRating: 4, country: "Portugal" },
    { name: "Ibis Lisboa Centro Saldanha", address: "Avenida Casal Ribeiro 23, 1000-090 Lisbon", starRating: 3, country: "Portugal" },
    { name: "Hotel Gat Rossio", address: "Rua do Jardim do Regedor 27-35, 1150-193 Lisbon", starRating: 3, country: "Portugal" },
    { name: "Hotel PortoBay Marquês", address: "Rua Duque de Palmela 32, 1250-098 Lisbon", starRating: 3, country: "Portugal" },
    { name: "Hotel Dom Carlos Park", address: "Avenida Duque de Loule 121, 1050-089 Lisbon", starRating: 3, country: "Portugal" },
    { name: "Holiday Inn Express Lisbon - Av. Liberdade", address: "Rua Alexandre Herculano 40, 1250-011 Lisbon", starRating: 3, country: "Portugal" },

    // Greece
    { name: "Hotel Grande Bretagne", address: "1 Vasileos Georgiou A' St, 105 64 Athens", starRating: 5, country: "Greece" },
    { name: "King George", address: "3 Vasileos Georgiou A' St, 105 64 Athens", starRating: 5, country: "Greece" },
    { name: "Canaves Oia Suites", address: "Oia, 84702 Santorini", starRating: 5, country: "Greece" },
    { name: "Blue Palace, a Luxury Collection Resort", address: "Plaka, Elounda, 720 53 Crete", starRating: 5, country: "Greece" },
    { name: "Santorini Secret Suites & Spa", address: "Oia, 84702 Santorini", starRating: 5, country: "Greece" },
    { name: "Electra Metropolis", address: "15 Mitropoleos St, 105 57 Athens", starRating: 4, country: "Greece" },
    { name: "Royal Olympic Hotel", address: "28-34 Athanasiou Diakou St, 117 43 Athens", starRating: 4, country: "Greece" },
    { name: "Athenaeum InterContinental", address: "89-93 Syngrou Ave, 117 45 Athens", starRating: 4, country: "Greece" },
    { name: "Radisson Blu Park Hotel", address: "10 Alexandras Ave, 106 82 Athens", starRating: 4, country: "Greece" },
    { name: "Melia Athens", address: "14 Chalkokondili St, 106 77 Athens", starRating: 4, country: "Greece" },
    { name: "Hotel Parthenon", address: "6 Makri St, 117 42 Athens", starRating: 3, country: "Greece" },
    { name: "Philippos Hotel", address: "3 Mitseon St, 117 42 Athens", starRating: 3, country: "Greece" },
    { name: "Athens Center Square Hotel", address: "15 Aristogitonos St, 105 52 Athens", starRating: 3, country: "Greece" },
    { name: "Acropolis Hill Hotel", address: "7 Mousson St, 117 42 Athens", starRating: 3, country: "Greece" },
    { name: "Hermes Hotel", address: "19 Apollonos St, 105 57 Athens", starRating: 3, country: "Greece" }

];

export default hotels;
